server:
  port: 80


eureka:
  client: #客户端注册进eureka服务列表中
    service-url:
      #efaultZone: http://localhost:7001/eureka #该地址在eureka 服务中暴露的 单机
      defaultZone: http://localhost7001:7001/eureka,http://localhost7002:7002/eureka,http://localhost7003:7003/eureka #该地址在eureka 服务中暴露的 单机
    #register-with-eureka: false  # 不注册自己
  instance:
    instance-id: spring_cloud_consumer_dept_feign_80
    prefer-ip-address: true  #访问路径显示ip地址
spring:
  application:
    name: springcloud-consumer-dept-feign