server:
  port: 8001
#对外暴露微服务名字
spring:
  application:
    name: springcloud-dept
eureka:
  client: #客户端注册进eureka服务列表中
    service-url:
      defaultZone: http://localhost:7001/eureka #该地址在eureka 服务中暴露的

